events {}

http {
    server {
        listen 80;
        server_name bedriften.no;

        location / {
            proxy_pass http://webapp:5000;
        }

        location /ansatte {
            proxy_pass http://webapp:5000/ansatte;
        }

        location /info {
            proxy_pass http://webapp:5000/info;
        }

        location /kontakt {
            proxy_pass http://webapp:5000/kontakt;
        }
    }
}
