# Leser Samba sine loggfiler via imfile-modulen
module(load="imfile")

# Overvåk Samba sin hovedlogg og send den videre til rsyslog
input(type="imfile"
      File="/var/log/samba/log.smbd"
      Tag="smbd"
      Severity="info"
      Facility="daemon")
